### ISSUE TITLE
BUG: fel bokstav i release titel

### ISSUE THREAD

**Issue by gosiacodes** [Sydow75/Michaela-Sydow-vh-slut_vg#52]
Det står v0.2-alpa i stället för v0.2-alpha. Dessutom v0.2-alpha var redan released, kanske det skulle vara bättre att ändra till nästa version / med annat nummer?

**Comment by Sydow75** [comment]
Handhavande av mig tydligen. Självklart är det version 0.3 och korrekt stavning.

**Comment by Sydow75** [comment]
Bug åtgärdat stänger ärendet. Korrekt release är v0.3-alpha.
