### ISSUE TITLE
Färschema är lite för ljus 

### ISSUE THREAD

**Issue by gosiacodes** [Sydow75/Michaela-Sydow-vh-slut_vg#53]
Kunden ville ha det med "svenkst" färschema. I issue står det i kommentar:
"Svenskt = blått och gult. Tänk på nyanser och kontrast.",
så kanske kan du ändra till mer gul färg i stället för "lightyellow"?
Vi kan vänta också vad kunden ska säga om det.

**Comment by Sydow75** [comment]
Hej, jag har varit i kontakt med kund och visat ändringar och kunden har accepterat ändringar per mail. Pga detta görs inga andra ändringar i färgschemat. Stänger ärendet.
