### ISSUE TITLE
Fixa css-fil

### ISSUE THREAD

**Issue by gosiacodes** [Sydow75/Michaela-Sydow-vh-slut_vg#54]
Om du har bara en fil med css, importeringar behövs inte längre, så det är bra om du kan ta bort det från koden:

@import url("navigation.css");
@import url("footer.css");
@import url("content.css");

**Comment by Sydow75** [comment]
Hej, tack. Ordnar det direkt, missades av mig. Stänger ärendet när klart.

**Comment by Sydow75** [comment]
Nu är det borttaget och uppdaterat main, tack för jättebra feedback, har lärt mig ngt nytt idag =). Avslutar ärendet.
