### ISSUE TITLE
Bra jobbat!

### ISSUE THREAD

**Issue by gosiacodes** [Sydow75/Michaela-Sydow-vh-slut_vg#55]
Det är jättebra att du har alla branscher stängda! Då issues / tasks som redan var markerad som ”done” kunde också stängas och du fick ändringar i projektet som Johan redan gjorde. 
I framtiden försök bara skapa ny branch för varje task / issue, så det är lättare att följa med projektet och ens versioner.
Bra jobbat Michaela! 😃

**Comment by Sydow75** [comment]
Tack tar det till mig. Mitt första arbeta på detta sätt. Givande och kul har det varit. Under arbetets gång har jag lärt mig ett och annat och nu förstår jag vikten av att arbeta i olika branch.
